// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtxSMOc2Ph-wO291JND9BxvkVqYgN4BAQ',
    appId: '1:352841966892:web:74c2fa17bccb7c5e3df889',
    messagingSenderId: '352841966892',
    projectId: 'indexer-54625',
    authDomain: 'indexer-54625.firebaseapp.com',
    storageBucket: 'indexer-54625.appspot.com',
    measurementId: 'G-T5S258FW1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5BnudbLf6EN-NCb-FM5MTuuEqaIIU4vs',
    appId: '1:352841966892:android:cf6f75d589a7b3573df889',
    messagingSenderId: '352841966892',
    projectId: 'indexer-54625',
    storageBucket: 'indexer-54625.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-38Vw5piZNPO-RTA2fWib_k2TR09WEQ',
    appId: '1:352841966892:ios:72d0e83227926df63df889',
    messagingSenderId: '352841966892',
    projectId: 'indexer-54625',
    storageBucket: 'indexer-54625.appspot.com',
    iosClientId:
        '352841966892-q9299hgjapq6ubapnee5uhj3s8658f2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.indexerClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-38Vw5piZNPO-RTA2fWib_k2TR09WEQ',
    appId: '1:352841966892:ios:72d0e83227926df63df889',
    messagingSenderId: '352841966892',
    projectId: 'indexer-54625',
    storageBucket: 'indexer-54625.appspot.com',
    iosClientId:
        '352841966892-q9299hgjapq6ubapnee5uhj3s8658f2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.indexerClient',
  );
}
